In [30]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

### Define path to data

In [31]:
base_path = "data/raw"

In [32]:
property_dict = {
    "A": ["NonPolar", 'Neutral', 'Hydrophobic', 'NonAromatic', 'NonIonizable'],
    "R": ["Polar", "Positive", 'Hydrophilic', 'NonAromatic', 'Ionizable'],
    "N": ["Polar", 'Neutral', 'Hydrophilic', 'NonAromatic', 'NonIonizable'],
    "D": ["Polar", "Negative", 'Hydrophilic', 'NonAromatic', 'Ionizable'],
    "C": ["Polar", 'Neutral', 'Hydrophilic', 'NonAromatic', 'Ionizable'],
    "Q": ["Polar", 'Neutral', 'Hydrophilic', 'NonAromatic', 'NonIonizable'],
    "E": ["Polar", "Negative", 'Hydrophilic', 'NonAromatic', 'Ionizable'],
    "G": ["NonPolar", 'Neutral', 'Hydrophobic', 'NonAromatic', 'NonIonizable'],
    "H": ["Polar", "Positive", 'Hydrophilic', 'NonAromatic', 'Ionizable'],
    "I": ["NonPolar", 'Neutral', 'Hydrophobic', 'NonAromatic', 'NonIonizable'],
    "L": ["NonPolar", 'Neutral', 'Hydrophobic', 'NonAromatic', 'NonIonizable'],
    "K": ["Polar", "Positive", 'Hydrophilic', 'NonAromatic', 'Ionizable'],
    "M": ["NonPolar", 'Neutral', 'Hydrophobic', 'NonAromatic', 'NonIonizable'],
    "F": ["NonPolar", 'Neutral', 'Hydrophobic', "Aromatic", 'NonIonizable'],
    "P": ["NonPolar", 'Neutral', 'Hydrophobic', 'NonAromatic', 'NonIonizable'],
    "S": ["Polar", 'Neutral', 'Hydrophilic', 'NonAromatic', 'NonIonizable'],
    "T": ["Polar", 'Neutral', 'Hydrophilic', 'NonAromatic', 'NonIonizable'],
    "W": ["NonPolar", 'Neutral', 'Hydrophobic', "Aromatic", 'NonIonizable'],
    "Y": ["Polar", 'Neutral', 'Hydrophobic', "Aromatic", 'Ionizable'],
    "V": ["NonPolar", 'Neutral', 'Hydrophobic', 'NonAromatic', 'NonIonizable']
}

### Transform property dictionary

In [33]:
mapping = {'Hydrophobic':0, 'Hydrophilic':1, 'Neutral':0, 'Positive':1, 'Negative':-1, 'Polar':1, 'NonPolar':0, 'Aromatic':1, 'NonAromatic':0, 'Ionizable':1, 'NonIonizable':0}


In [35]:
prop_arr = np.asarray([v for v in property_dict.values()])
# for i in range(len(prop_arr[:,0]

In [36]:
feature_dict = {}
for key in property_dict.keys():
    vals = [mapping[p] for p in property_dict[key]]
    feature_dict[key.lower()] = vals

In [37]:
feature_dict

{'a': [0, 0, 0, 0, 0],
 'r': [1, 1, 1, 0, 1],
 'n': [1, 0, 1, 0, 0],
 'd': [1, -1, 1, 0, 1],
 'c': [1, 0, 1, 0, 1],
 'q': [1, 0, 1, 0, 0],
 'e': [1, -1, 1, 0, 1],
 'g': [0, 0, 0, 0, 0],
 'h': [1, 1, 1, 0, 1],
 'i': [0, 0, 0, 0, 0],
 'l': [0, 0, 0, 0, 0],
 'k': [1, 1, 1, 0, 1],
 'm': [0, 0, 0, 0, 0],
 'f': [0, 0, 0, 1, 0],
 'p': [0, 0, 0, 0, 0],
 's': [1, 0, 1, 0, 0],
 't': [1, 0, 1, 0, 0],
 'w': [0, 0, 0, 1, 0],
 'y': [1, 0, 0, 1, 1],
 'v': [0, 0, 0, 0, 0]}

## Notes

The RF was trained in a 5-fold cross-validation manner training on 4 of the 5 partitions using the epitope residues (positive dataset) and a subset of randomly selected non-epitope residues (negative dataset)

Each amino acid was encoded using the volume (5), hydrophobicity (6) and polarity (7) combined with the relative surface accessibility (RSA) and secondary structure (SS) predicted using NetsurfP (8).

Possible feature: Sum of volumes of residues (equation 1 in supple)

### Load epitope data of SARS

In [38]:
data = pd.read_csv(os.path.join(base_path, "epitope_table_export_1582825906.csv"))

In [39]:
epitopes_sars = data["Epitope.2"][1:]

In [40]:
for epi in epitopes_sars:
    print(epi)

AALVSGTATAGWTFGAG
AATKMSECVLGQSKRVD
AATVLQLPQGTTLPK
AAYFVGYLKPTTFMLKY
AGCLIGAEHVDTSYECD
AIPTNFSISITTEVMPV
AISSVLNDILSRLDKVE
ALALLLLDRLNQLESKV
ALNCYW
ALNCYWPLNDYGFYTTTGIGYQPYRVVVLSFEL + ACET(A1)
AMDPIYDEPTTTTSVPL
AMQMAYRF
ANKEGIVWVATEGALN
APRITFGGPTDSTDNNQN
AQKFNGLTVLPPLLTDD
ASSRSSSRSRGNSRNST
ASWFTALTQHGKEELRFPRGQ
ATEKSNVVRGWV
AYFPREGVFVFNGTSWF
AYSNNTIAIPTNFSISI
CANLLLQYGSFCTQLNRALSGIA
CASYHTVSLLRSTSQKS
CDIPIGAGICASYHTVS
CGPKLSTDLIKNQCVNF
CGPKLSTDLIKNQCVNFNFNGLTGTGVLTPSSKRFQPFQQFG
CGPKLSTDLIKNQCVNFNFNGLTGTGVLTPSSKRFQPFQQFGRDVSDFTD
CKFDEDDSEPVLKGVKLHYT
CSQNPLAELKCSVKSFE
CSQNPLAELKCSVKSFEIDKGIYQTSNFRVVPSGD
CTDVSTAIHADQLTPAW
CTDVSTAIHADQLTPAWRIYSTGNNVFQTQAG
CTPPALNCYWPLNDYGF
CTTFDDVQAPNYTQHTSSMRGVYYPDEIFR
CVLAWNTRNIDATSTGN
CYGVSATKLNDLCFSNV
CYWPLNDYGFYTTTGIG
DDKDPQFKDNVILLNKHIDA
DDSEPVLKGVKLHYT
DFCGKGYHLMSFPQAAP
DFSRQLQNSMSGASA
DGIYFAATEKSNVVRGW
DLGDISGINASVVNIQK
DLPSGFNTLKPIFKLPL
DMIAAYTAALVSGTATA
DNIKDC
DRCTTFDDVQAPNYTQH
DRLNQLESKVSGKGQQQQ
DVNLHSSR
DVSEKSGNFKHLREFVF
DVVNQNAQALNTLVKQL
EAE

In [41]:
print("mean epitope length:", np.mean([len(epi) for epi in epitopes_sars])) # , return_counts=True)

mean epitope length: 17.42


### Load structural data of paper

In [42]:
with open(os.path.join(base_path, "pdb_chains.fasta.txt"), "r") as infile:
    txt = infile.read()
structured = txt.split(">")[1:]

In [113]:
struct_metadata = list()
struct_sequ = list()
struct_lab_arr = list()
for entry in structured:
    split_entry = entry.split("\n")
    struct_metadata.append(split_entry[0])
    struct_sequ.append(split_entry[1])
    labels = [int(s.isupper()) for s in split_entry[1]]
    struct_lab_arr.append(labels)
struct_lab_arr = np.array(struct_lab_arr)

In [44]:
# TESTING
print(struct_sequ[20])
print(struct_lab_arr[20])

statlclghhavpngtlvktitddqievtnatelvqsssTGKicnnphriLDgIDctlidallgdPHcdVFqnEtwdlfveRsKaFsncypydvpdyaslrslvassgtlefitegftwtgvtqnggsnackrgpgsgffsrlnwltksgstypvlnvtmpnndnfdklyiwgihhpstnqeqtslyvqasgrvtvstrrsqqtiipnigsrpwvrglssrisiywtivkpgdvlvinsngnliaprgyfkmrtgkssimrsDAPIdtcisecitpngsipndkpfqnvnkitygacpkyvkqntlklatgmrnvpekq
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

In [46]:
print("number amino acids", len("".join(struct_sequ)), "number sequences", len(struct_lab_arr))

number amino acids 183887 number sequences 776


### Load linear data of paper

In [47]:
with open(os.path.join(base_path, "iedb_linear_epitopes.fasta.txt"), "r") as infile:
    txt_linear = infile.read()

In [48]:
linear = txt_linear.split(">")[1:]

In [49]:
linear_metadata = list()
linear_sequ = list()
linear_epi = list()
linear_labs = list()
for entry in linear:
    split_entry = entry.split("\n")
    if split_entry[0][:3]=="Pos":
        linear_labs.append(1)
    elif split_entry[0][:3]=="Neg":
        linear_labs.append(0)
    linear_metadata.append(split_entry[0][9:])
    linear_sequ.append(split_entry[1])
    linear_epi.append("".join([s for s in split_entry[1] if s.isupper()]))

In [50]:
# TESTING
test_int = 50
print(linear[test_int])
print(linear_sequ[test_int])
print(linear_epi[test_int])
print(linear_labs[test_int])

PositiveID_46198
msdngpqsnqrsapritfggptdstdnnqnggrngarpkqrrpqglpnntaswftaltqhgkeelrfprgqgvpiNTNSGPDDQIGYYRRATRrvrggdgkmkelsprwyfyylgtgpeaslpygankegivwvategalntpkdhigtrnpnnnaatvlqlpqgttlpkgfyaegsrggsqassrsssrsrgnsrnstpgssrgnsparmasgggetalalllldrlnqleskvsgkgqqqqgqtvtkksaaeaskkprqkrtatkqynvtqafgrrgpeqtqgnfgdqdlirqgtdykhwpqiaqfapsasaffgmsrigmevtpsgtwltyhgaiklddkdpqfkdnvillnkhidayktfpptepkkdkkkktdeaqplpqrqkkqptvtllpaadmddfsrqlqnsmsgasadstqa

msdngpqsnqrsapritfggptdstdnnqnggrngarpkqrrpqglpnntaswftaltqhgkeelrfprgqgvpiNTNSGPDDQIGYYRRATRrvrggdgkmkelsprwyfyylgtgpeaslpygankegivwvategalntpkdhigtrnpnnnaatvlqlpqgttlpkgfyaegsrggsqassrsssrsrgnsrnstpgssrgnsparmasgggetalalllldrlnqleskvsgkgqqqqgqtvtkksaaeaskkprqkrtatkqynvtqafgrrgpeqtqgnfgdqdlirqgtdykhwpqiaqfapsasaffgmsrigmevtpsgtwltyhgaiklddkdpqfkdnvillnkhidayktfpptepkkdkkkktdeaqplpqrqkkqptvtllpaadmddfsrqlqnsmsgasadstqa
NTNSGPDDQIGYYRRATR
1


In [51]:
print("class balance", np.unique(linear_labs, return_counts=True))

class balance (array([0, 1]), array([18722, 11834]))


### Define features

In [90]:
feature_dict["x"] = [0.5 for _ in range(5)]

In [93]:
def pad_seq(seq, pad_len=10):
    return "".join(["x" for _ in range(pad_len)])+seq+"".join(["x" for _ in range(pad_len)])

In [104]:
def seq2features(seq, window_r=4):
    seq_padded = pad_seq(seq, pad_len=window_r)
    feats = np.array([feature_dict[s.lower()] for s in seq_padded])
    window_feats = np.array([feats[i-window_r:i+window_r+1] for i in range(window_r, len(seq)+window_r)])
    return window_feats

In [108]:
seq2features(linear_epi[20]).shape

(11, 9, 5)

In [54]:
print(linear_epi[20])
print(seq2features(linear_epi[20]))

TNGTSGRTPVL
[[1 0 1 0 0]
 [1 0 1 0 0]
 [0 0 0 0 0]
 [1 0 1 0 0]
 [1 0 1 0 0]
 [0 0 0 0 0]
 [1 1 1 0 1]
 [1 0 1 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [ ]:
# jede aminosäure 45 features
# 1d convolution auf je 45 features
# spalte: protein-id, position im 

### Prepare structured data for CNN

In [63]:
from sklearn.model_selection import train_test_split

In [ ]:
flattened_df_cols[2]

In [70]:
x_train, x_test, y_train, y_test = train_test_split(struct_sequ, struct_lab_arr, test_size=0.1, random_state=1)

x_train, x_val, y_train, y_val = train_test_split(x_train, y_train, test_size=0.2, random_state=1)

In [72]:
print("train:", x_train.shape, y_train.shape,"val:", x_val.shape, y_val.shape, "test:", x_test.shape, y_test.shape)

train: (558,) (558,) val: (140,) (140,) test: (78,) (78,)


In [62]:
inds = np.random.permutation(len(struct_sequ))
nr_train = len(inds)//5
train = data_struct[inds[:nr_train]]

776

In [86]:
data_struct = [seq2features(seq) for seq in x_train]
x_inp = np.concatenate(data_struct, axis=0)

In [88]:
y_inp = np.concatenate(y_train, axis=0)
print(x_inp.shape, y_inp.shape)

(133036, 5) (133036,)


## Prepare dataframe:

In [157]:
df_cols = [[] for _ in range(6)]
for i in range(len(struct_sequ)):
    sequ_len = len(struct_sequ[i])
    # our id column
    df_cols[0].append(np.array([i for _ in range(sequ_len)]))
    # metadata column
    df_cols[1].append(np.array([struct_metadata[i] for _ in range(sequ_len)]))
    # position in this sequence
    df_cols[2].append(np.arange(0,sequ_len, 1))
    # actual amino acid
    df_cols[3].append(list(struct_sequ[i]))
    # actual data
    df_cols[4].append(seq2features(struct_sequ[i], window_r=4))
    # labels
    df_cols[5].append(struct_lab_arr[i])

In [158]:
flattened_df_cols = [np.concatenate(df_cols[i]) for i in range(6)]

In [159]:
names = ["our_id", "metadata", "position", "amino_acid", "data", "labels"]
df = pd.DataFrame()

In [160]:
for i in range(6):
    df[names[i]] = pd.Series(flattened_df_cols[i].tolist())

In [ ]:
out_path = "data"

In [163]:
df.to_csv(os.path.join(out_path, "data_struct_features.csv"))

In [162]:
len(df)

183887

In [161]:
df.head(20)

our_id     metadata  position amino_acid  \
0        0  1A2Y_BA C 2         0          k   
1        0  1A2Y_BA C 2         1          v   
2        0  1A2Y_BA C 2         2          f   
3        0  1A2Y_BA C 2         3          g   
4        0  1A2Y_BA C 2         4          r   
5        0  1A2Y_BA C 2         5          c   
6        0  1A2Y_BA C 2         6          e   
7        0  1A2Y_BA C 2         7          l   
8        0  1A2Y_BA C 2         8          a   
9        0  1A2Y_BA C 2         9          a   
10       0  1A2Y_BA C 2        10          a   
11       0  1A2Y_BA C 2        11          m   
12       0  1A2Y_BA C 2        12          k   
13       0  1A2Y_BA C 2        13          r   
14       0  1A2Y_BA C 2        14          h   
15       0  1A2Y_BA C 2        15          g   
16       0  1A2Y_BA C 2        16          l   
17       0  1A2Y_BA C 2        17          a   
18       0  1A2Y_BA C 2        18          N   
19       0  1A2Y_BA C 2        19          y   

                                                 data  labels  
0   [[0.5, 0.5, 0.5, 0.5, 0.5], [0.5, 0.5, 0.5, 0....       0  
1   [[0.5, 0.5, 0.5, 0.5, 0.5], [0.5, 0.5, 0.5, 0....       0  
2   [[0.5, 0.5, 0.5, 0.5, 0.5], [0.5, 0.5, 0.5, 0....       0  
3   [[0.5, 0.5, 0.5, 0.5, 0.5], [1.0, 1.0, 1.0, 0....       0  
4   [[1.0, 1.0, 1.0, 0.0, 1.0], [0.0, 0.0, 0.0, 0....       0  
5   [[0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 1....       0  
6   [[0.0, 0.0, 0.0, 1.0, 0.0], [0.0, 0.0, 0.0, 0....       0  
7   [[0.0, 0.0, 0.0, 0.0, 0.0], [1.0, 1.0, 1.0, 0....       0  
8   [[1.0, 1.0, 1.0, 0.0, 1.0], [1.0, 0.0, 1.0, 0....       0  
9   [[1.0, 0.0, 1.0, 0.0, 1.0], [1.0, -1.0, 1.0, 0...       0  
10  [[1.0, -1.0, 1.0, 0.0, 1.0], [0.0, 0.0, 0.0, 0...       0  
11  [[0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0....       0  
12  [[0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0....       0  
13  [[0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0....       0  
14  [[0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0....       0  
15  [[0.0, 0.0, 0.0, 0.0, 0.0], [1.0, 1.0, 1.0, 0....       0  
16  [[1.0, 1.0, 1.0, 0.0, 1.0], [1.0, 1.0, 1.0, 0....       0  
17  [[1.0, 1.0, 1.0, 0.0, 1.0], [1.0, 1.0, 1.0, 0....       0  
18  [[1.0, 1.0, 1.0, 0.0, 1.0], [0.0, 0.0, 0.0, 0....       1  
19  [[0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0....       0